version: '3'
services:
  db:
    image: mariadb:10.4
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_ROOT_PASSWORD: AppleSucks
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    networks:
      - custom-driver
  drupal:
    depends_on:
      - db
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./app:/app
    restart: always
    networks:
      - custom-driver
volumes:
  db_data:

networks:
  driver: custom-driver